backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "sections"
    label: "الأقسام"
    file: "sections.json"
    fields:
      - label: "القسم"
        name: "sections"
        widget: "list"
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "الوصف", name: "description", widget: "string" }
          - { label: "الصورة", name: "image", widget: "string" }
          - { label: "الرابط", name: "link", widget: "string" }
          - { label: "نص الزر", name: "button", widget: "string" }